config/routes.rb
Houndapp::Application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources(
        dashboard_resource,
        controller: "application",
        resource_class: dashboard_resource,
      )
    end

    root to: "application#index", resource_class: :bulk_customers
  end

  mount Resque::Server, at: "/queue"
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  mount Split::Dashboard, at: "split"

  get "/auth/github/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"
  get "/configuration", to: "pages#configuration"
  get "/faq", to: "pages#show", id: "faq"

  resource :account, only: [:show, :update]
  resources :builds, only: [:create]

  resources :repos, only: [:index] do
    with_options(defaults: { format: :json }) do
      resource :activation, only: [:create]
      resource :deactivation, only: [:create]
      resource :subscription, only: [:create, :destroy]
    end
  end

  with_options(defaults: { format: :json }) do
    resource :credit_card, only: [:update]
    resources :repo_syncs, only: [:index, :create]
    resource :user, only: [:show]
  end

  %w(404 422 500).each do |status_code|
    get status_code, to: "errors#show", code: status_code
  end

  root to: "home#index"
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < Administrate::ApplicationController
  before_action :authenticate_admin

  private

  def controller_path
    params[:resource_class].to_s
  end

  def authenticate_admin
    unless github_admin?
      redirect_to :root
    end
  end

  def github_admin?
    current_user && admin_github_handles.include?(current_user.github_username)
  end

  def current_user
    @current_user ||= User.find_by(remember_token: session[:remember_token])
  end

  def admin_github_handles
    ENV.fetch("ADMIN_GITHUB_USERNAMES", "").split(",")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :force_https
  before_action :capture_campaign_params
  before_action :authenticate

  helper_method :current_user, :signed_in?

  private

  def force_https
    if Hound::HTTPS_ENABLED
      if !request.ssl? && force_https?
        redirect_to protocol: "https://", status: :moved_permanently
      end
    end
  end

  def force_https?
    true
  end

  def capture_campaign_params
    session[:campaign_params] ||= {
      utm_campaign: params[:utm_campaign],
      utm_medium: params[:utm_medium],
      utm_source: params[:utm_source],
    }
  end

  def authenticate
    unless signed_in?
      redirect_to root_path
    end
  end

  def signed_in?
    current_user.present? && current_user.token.present?
  end

  def current_user
    @current_user ||= User.where(remember_token: session[:remember_token]).first
  end

  def analytics
    @analytics ||= Analytics.new(current_user, session[:campaign_params])
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email_address.downcase)
    "https://www.gravatar.com/avatar/#{gravatar_id}"
  end

  def display_onboarding?
    Build.
      joins(repo: :memberships).
      where(memberships: { user_id: current_user.id }).
      empty?
  end
end

app/views/application/_analytics.haml
:javascript
  window.analytics||(window.analytics=[]),window.analytics.methods=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var method=window.analytics.methods[i];window.analytics[method]=window.analytics.factory(method)}window.analytics.load=function(t){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)},window.analytics.SNIPPET_VERSION="2.0.8",
  window.analytics.load("#{Hound::SEGMENT_KEY}");

- if flash[:signed_up]
  :javascript
    window.analytics.alias("#{current_user.id}");

- if signed_in?
  :javascript
    window.analytics.identify(
      "#{current_user.id}",
      #{raw identify_hash.to_json},
      #{raw intercom_hash.to_json}
    );
- else
  :javascript
    var links = document.getElementsByClassName("auth");

    for (var i = 0; i < links.length; i++) {
      window.analytics.trackLink(
        links[i],
        "Clicked Sign In",
        { variation: "#{ab_test("auth_button")}" }
      );
    }

- if flash[:signed_up]
  :javascript
    window.analytics.track("Signed Up", #{raw campaign_hash.to_json});

:javascript
  window.analytics.page(
    "#{j content_for(:page_title)}",
    #{raw campaign_hash.to_json}
  );

= yield :analytics

app/views/application/_auth_button.haml
= link_to "/auth/github", class: "auth" do
  %i.fa.fa-github
  %span= ab_test("auth_button")

app/views/application/_footer.haml
%footer
  %ul.footer-nav
    %li
      = link_to "Source Code", "https://github.com/thoughtbot/hound"
    %li
      = link_to "FAQ", faq_path
    %li
      = link_to "Terms", "https://github.com/thoughtbot/hound/blob/master/doc/TERMS.md"
    %li
      = link_to "Privacy", "https://github.com/thoughtbot/hound/blob/master/doc/PRIVACY.md"
    %li
      = link_to "Security", "https://github.com/thoughtbot/hound/blob/master/doc/SECURITY.md"

  %article.legal
    %p
      Hound is maintained by #{link_to 'thoughtbot', 'http://thoughtbot.com'}.
      Questions? Try the
      #{link_to "FAQ", faq_path} or
      Tweet #{link_to "@houndci", "https://twitter.com/houndci", target: "_blank"}.

    %p
      Hound is Copyright &copy; #{Date.today.year} thoughtbot. It is open source
      software and may be redistributed under the terms specified in the
      #{link_to "LICENSE", "https://github.com/thoughtbot/hound/blob/master/LICENSE"}.

    %p
      The names and logos for Hound are trademarks of thoughtbot.

app/views/application/_header.haml
%header.global-header{ class: content_for(:header_class) }
  .logo.pull-left
    .va-cell
      = link_to repos_path, class: "logo-link" do
        %h1
          Hound
  %ul.pull-left
    %li
      = link_to "Docs", configuration_path, class: "docs"
    %li
      = link_to "FAQ", faq_path, class: "faq"
  %ul.pull-right
    - if signed_in?
      %li
        = link_to account_path, class: "account" do
          - if current_user.email_address.present?
            .avatar(style="background-image: url('#{avatar_url(current_user)}')")
          %span #{current_user.github_username}
      %li
        = link_to t("sign_out"), sign_out_path, class: "sign-out"
    - else
      %li
        = link_to "Pricing", root_path(anchor: "pricing"), class: "pricing"
      %li
        = link_to "https://twitter.com/houndci", target: "_blank", class: "tweet-us" do
          %span @houndci
      %li.auth-container
        = render "application/auth_button"

app/views/application/_preload_template.haml
%script{ type: 'text/ng-template', id: "/templates/#{template}" }
  = render template: "/templates/#{template}"

app/views/application/_settings.haml
:javascript
  Namespaced.declare("Hound.settings");
  Hound.settings = {
    stripePublishableKey: "#{Hound::STRIPE_PUBLISHABLE_KEY}",
    userEmailAddress: "#{current_user.email_address}",
  };